'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\server\ClientApps\In-House\Path Structure.xml")>  _
        Public Property SettingsPath() As String
            Get
                Return CType(Me("SettingsPath"),String)
            End Get
            Set
                Me("SettingsPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property blnAddAll() As Boolean
            Get
                Return CType(Me("blnAddAll"),Boolean)
            End Get
            Set
                Me("blnAddAll") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property blnAddSingle() As Boolean
            Get
                Return CType(Me("blnAddSingle"),Boolean)
            End Get
            Set
                Me("blnAddSingle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property blnFormat() As Boolean
            Get
                Return CType(Me("blnFormat"),Boolean)
            End Get
            Set
                Me("blnFormat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property blnAudit() As Boolean
            Get
                Return CType(Me("blnAudit"),Boolean)
            End Get
            Set
                Me("blnAudit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property blnClipboard() As Boolean
            Get
                Return CType(Me("blnClipboard"),Boolean)
            End Get
            Set
                Me("blnClipboard") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property blnTransferByExtension() As Boolean
            Get
                Return CType(Me("blnTransferByExtension"),Boolean)
            End Get
            Set
                Me("blnTransferByExtension") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=server;Initial Catalog=IRONGATE;User ID=IrongateApplications;Password"& _ 
            "=App2014!Dev")>  _
        Public Property ERPConnection() As String
            Get
                Return CType(Me("ERPConnection"),String)
            End Get
            Set
                Me("ERPConnection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property blnERPCheck() As Boolean
            Get
                Return CType(Me("blnERPCheck"),Boolean)
            End Get
            Set
                Me("blnERPCheck") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property blnPreview() As Boolean
            Get
                Return CType(Me("blnPreview"),Boolean)
            End Get
            Set
                Me("blnPreview") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property blnReportErrors() As Boolean
            Get
                Return CType(Me("blnReportErrors"),Boolean)
            End Get
            Set
                Me("blnReportErrors") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property blnReportInformation() As Boolean
            Get
                Return CType(Me("blnReportInformation"),Boolean)
            End Get
            Set
                Me("blnReportInformation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property blnReportOptimal() As Boolean
            Get
                Return CType(Me("blnReportOptimal"),Boolean)
            End Get
            Set
                Me("blnReportOptimal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property blnFolderHeatMap() As Boolean
            Get
                Return CType(Me("blnFolderHeatMap"),Boolean)
            End Get
            Set
                Me("blnFolderHeatMap") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property blnDeleteThumbsDb() As Boolean
            Get
                Return CType(Me("blnDeleteThumbsDb"),Boolean)
            End Get
            Set
                Me("blnDeleteThumbsDb") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property blnDirectArchive() As Boolean
            Get
                Return CType(Me("blnDirectArchive"),Boolean)
            End Get
            Set
                Me("blnDirectArchive") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property blnSetPermissions() As Boolean
            Get
                Return CType(Me("blnSetPermissions"),Boolean)
            End Get
            Set
                Me("blnSetPermissions") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Ctrl+F3")>  _
        Public Property keyWatcherSearch() As Global.System.Windows.Forms.Keys
            Get
                Return CType(Me("keyWatcherSearch"),Global.System.Windows.Forms.Keys)
            End Get
            Set
                Me("keyWatcherSearch") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("yyyy-MM-dd")>  _
        Public Property strTimeStampFormat() As String
            Get
                Return CType(Me("strTimeStampFormat"),String)
            End Get
            Set
                Me("strTimeStampFormat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\server\clientapps\In-House\Path Structure\Plugins")>  _
        Public Property strPluginDirectory() As String
            Get
                Return CType(Me("strPluginDirectory"),String)
            End Get
            Set
                Me("strPluginDirectory") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Path_Structure_Maintenance.My.MySettings
            Get
                Return Global.Path_Structure_Maintenance.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
